mstable/MIPs

MIPS/mip-x.md

Adds a Liquidator Component Proposal

Add Liquidator Component

---

MIPS/mip-2.md

Publishing MIP-2 after assigning number.

Publish MIP-2

---

CNAME
MIPS/mip-3.md

Depositing and withdrawing from lending markets (Compound, Aave) constitutes
70-90% of the gas cost of a given transaction. This MIP proposes to implement a
cache to reduce frequency of interactions with the lending pools.
We propose upgrading the `Masset.sol` contract, allowing it to track and retain a percentage of
all collateral in it's "cache". Only if necessary will the `Masset` then deposit or withdraw from
the lending markets. Subsequently, the `BasketManager.sol` will be upgraded to use the cache data
during normal interest collection.

Proposal of bAsset cache

---

MCCP/mccp-3.md

My first go at creating files and doing Github stuff. Yeet! Here's the text for mccp-3.
I have used the previous mccp raw text as template and pasted in the relevant content for the new proposal. Please check for any basic noob formatting errors that I may have made as this is my first time.

MCCP-3: Increase Save liquidator's weekly USD contribution

---

MCCP/mccp-7.md

Add MCCP 7

---

MIPS/mip-13.md

MIP 13: Bump status

---

MIPS/mip-15.md

Bump MIP-15 status from WIP to Implemented

Bump status

---

MIPS/mip-15.md

Small correction in the multiplier formular

---

MIPS/mip-16.md

Create MIP 16

---

MIPS/mip-20.md
MIPS/mip-21.md

edit mip 21 & mip 20

---

MIPS/mip-19.md

Update status of MIP-19 to Rejected

---

TDP/tdp-27.md

Add TDP 27

---

TDP/tdp-27.md
TDP/tdp-28.md

Updating TDP 27 and Publishing TDP 28 for release on the forum.

Update TDP 27 Header & Publish TDP 28

---

MIPS/mip-22.md

Tiers threshold + rules for existing partners

Updated MIP22

---

TDP/tdp-28.md
TDP/tdp-29.md

@dimsome can you please review ser?

Create TDP 29

---

.gitignore
MIPS/mip-24.md
TDP/tdp-20.1.md
TDP/tdp-20.2.md
TDP/tdp-20.3.md
TDP/tdp-21.1.md
TDP/tdp-21.2.md
TDP/tdp-22.md
TDP/tdp-23.1.md
TDP/tdp-23.2.md
TDP/tdp-24.1.md
TDP/tdp-24.2.md
TDP/tdp-27.md
TDP/tdp-28.md
TDP/tdp-29.md

Add tdps batch

---

MIPS/mip-17.md
MIPS/mip-22.md
MIPS/mip-24.md
TDP/tdp-27.md
TDP/tdp-28.md
TDP/tdp-29.md

bump status TDP 27, 28, 29 and MIP 19, 24

---

MIPS/mip-24.md

small fix to show the formula in MIP 24

fix: formula mip-24

---

TDP/tdp-33.md

Adding TDP 33 for Community subDAO creation and funding request. @dimsome

Add TDP 33

---

MCCP/mccp-12.md

MCCP 12 to whitelist Balancer DAO multisig in Staking V2

Add MCCP 12

---

MCCP/mccp-12.md

bump status MCCP-12

---

MIPS/mip-25.md

Add MIP-25

---

MCCP/mccp-14.md
MIPS/mip-18.md
MIPS/mip-22.md

chore: bump status

---

MIPS/mip-25.md

WIP, need to clarify vault upgrade on Polygon @doncesarts

add mip 25

---

TDP/tdp-28.md
TDP/tdp-29.md
TDP/tdp-30.md
TDP/tdp-31.md
TDP/tdp-32.md
TDP/tdp-33.md

Hi @dimsome,
can you please have a quick peek & merge these? Just updated the headers on some TDPs and corrected a minor typo in TDP 32.

Updating TDP Headers

---

MCCP/mccp-12.md
MCCP/mccp-13.md
MCCP/mccp-14.md
MCCP/mccp-15.md
MIPS/mip-23.md
MIPS/mip-24.md

bump statuses, added forum links and added MCCP 15

Add mccp 15

---

TDP/tdp-32.md
TDP/tdp-34.md

Hi @dimsome - can you please have  quick peek and merge if ok? :) Thank you!

Add TDP 34 & Update TDP 32 Header

---

TDP/tdp-34.md
TDP/tdp-35.md

gm @dimsome 
Could you please review and merge when possible? :) 
Thank you!

Add TDP 35 & Update TDP 34 Header

---

TDP/tdp-34.md
TDP/tdp-35.md
TDP/tdp-36.md

Hi @dimsome,
Can you please have a look here and merge if ok? :) 
Thanks!

TDP 36 & Update Headers

---

MCCP/mccp-17.md
MCCP/mccp-18.md
MCCP/mccp-19.md

Add MCCP 19

---

MCCP/mccp-18.md

- added endRecipient address
- added description to what happens after the rewardsForwarder adds the rewards

adjust MCCP 18

---

MCCP/mccp-18.md
MCCP/mccp-19.md
MIPS/mip-26.md
TDP/tdp-35.md
TDP/tdp-36.md
TDP/tdp-37.md

Hi @dimsome 
I added TDP 37 and updated a bunch of outdated headers. Would be great if you could quickly review and merge, thanks!

Add TDP 37 & Update a bunch of Headers

---

MCCP/mccp-19.md

fix: wrong parameter

---

TDP/tdp-40.md
TDP/tdp-41.md

Hi @dimsome san, can you please review and merge when you got a moment? Thank you!

Add TDP 41 & Update Header

---

MIPS/mip-27.md

add MIP 27

---

MCCP/mccp-18.md

Updated the proposal with the new `endRecipient` contract address.

Amend endRecipient

---

MCCP/mccp-18.md
MCCP/mccp-21.md

chore: bump statuses

---

TDP/tdp-36.md
TDP/tdp-39.md
TDP/tdp-40.md
TDP/tdp-41.md
TDP/tdp-42.md

Hi @dimsome san,
could you please review TDP 42 & the changes to the headers made? 
Thank you and have a great day! 😊

Add TDP 42 & Update Headers

---

TDP/tdp-42.md
TDP/tdp-43.md

Hi @dimsome 
Can you please review and merge when possible? Thank you very much!

Add TDP 43 & Update Header

---

MCCP/mccp-16.md
MCCP/mccp-18.md
MCCP/mccp-20.md
MCCP/mccp-22.md
MIPS/mip-17.md
MIPS/mip-26.md
MIPS/mip-27.md

add mccp 22 and other bumps

---

TDP/tdp-44.md

Hi @dimsome,
can you please review the smol change and merge in anticipation of the Builder subDAO vote winning? Can ofc wait as well :) 
Thanks!

Update TDP 44

---

TDP/tdp-45.md

Happy Friday @dimsome 
Could you please review and merge so we can get this out before the weekend to give enough time for concurrent discussions on the forum? 
ty!

Add TDP 45

---

TDP/tdp-45.md

Hi @dimsome,
can you please review and merge my typo from last week? 
Thanks a lot! :)

Fix TDP 45 Typo & Update Header

---

TDP/tdp-45.md
TDP/tdp-46.md

gm @dimsome 
Could you please review and approve? Many thanks, and happy Friday!

Add TDP 46 & Update Header

---

TDP/tdp-42.md
TDP/tdp-43.md
TDP/tdp-44.md
TDP/tdp-45.md
TDP/tdp-46.md

Hi @dimsome 
Can you please review the changes (especially in regards to the new-found consensus and poll results) and then let me know if all is gud? 
Thank you very much and have a great start into this week!

Update TDP 45 with Consensus & Update TDP Headers

---

TDP/tdp-45.md
TDP/tdp-46.md

Hi @dimsome 
as per our quick call, please check if it's satisfactory now regarding the seats, and i'll update the thread once approved!
Thank you!

Updates TDP 45 & 46

---

TDP/tdp-47.md

gm @dimsome 
can you please review? Many thanks!

Add TDP 47

---

TDP/tdp-45.md
TDP/tdp-46.md
TDP/tdp-47.md

gm @dimsome 
Can you please review and merge? I changed mainly the Core Contributor naming to Signer as per poll result, and also updated some minor header changes

Update TDP 45 & Headers

---

TDP/tdp-47.md

Hi @dimsome 
Can you please review these minor changes based upon feedback provided by @camsoulsby? 
Thank you!

Update TDP 47 Wording

---

MCCP/mccp-24.md

bump status to accepted & fix number of epochs from 612 to 624

Fix mccp 24

---

TDP/tdp-49.md
TDP/tdp-50.md

Happy Friday herr @dimsome, 
Could you please review this and merge when possible? Not immediate, as will publish on Monday barring no strong objections or changes :)

Add TDP 50

---

TDP/tdp-51.md

Fix one small link in Jeshli's PR

fix: copyright link add 

---

TDP/tdp-54.md

@dimsome resubmitting TDP 54 with only that file and with fixed requested changes

Resubmit TDP 54

---

TDP/tdp-48.md
TDP/tdp-49.md
TDP/tdp-50.md
TDP/tdp-51.md
TDP/tdp-52.md
TDP/tdp-53.md

Can you please review when time permits @dimsome?

Add TDP 52 and TDP 53 & Update Headers

---

MCCP/mccp-23.md
MCCP/mccp-24.md
MIPS/mip-29.md
TDP/tdp-52.md
TDP/tdp-53.md
TDP/tdp-54.md

gm @dimsome,
can you please review and merge? 
ty!

Publish MIP 29 & Update Headers

---

MIPS/mip-29.md

gm @dimsome 
can you please review the updated changes for MIP 29? 
TY :)

Update MIP 29

---

MIPS/mip-31.md

adjust MIP numbering

---

MIPS/mip-30.md
TDP/tdp-55.md

gm @dimsome 
Can you please review both of these and merge if fine? 
Thank you!

Publish MIP 30 & TDP 55

---

TDP/tdp-55.md

fix relative link

---

TDP/tdp-55.md

fix addresses

---

MIPS/mip-33.md

Adding MIP 33 - dHEDGE Acquisision of mStable

Add MIP 33 - dHEDGE Acquisition of mStable

---

MIPS/mip-34.md

Update and rename mip-34_origin.md to mip-34.md

---

TDP/tdp-55.md

hi @dimsome 
Updated TDP 55 to reflect the singular signer change only now. Can you please review? 
THanks!

Update TDP 55

---

MIPS/mip-35.md

add MIP-35
